// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgGxEcP3fzGEfsaLcgnZIJUxoLImrbbWs',
    appId: '1:972588904282:web:7bd6d60f63197d2fa84d63',
    messagingSenderId: '972588904282',
    projectId: 'taskotel',
    authDomain: 'taskotel.firebaseapp.com',
    storageBucket: 'taskotel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhXtQRUky_hN3unSXi0yFQ0CmyoQr1VTI',
    appId: '1:972588904282:android:a7db2fada94980b1a84d63',
    messagingSenderId: '972588904282',
    projectId: 'taskotel',
    storageBucket: 'taskotel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6BIt_Yo66qj3G-aOqLqEkgVegSwYBqMM',
    appId: '1:972588904282:ios:e9d3601b1e7154f0a84d63',
    messagingSenderId: '972588904282',
    projectId: 'taskotel',
    storageBucket: 'taskotel.firebasestorage.app',
    iosBundleId: 'com.diwizon.taskoteladmin',
  );
}
